- name: Run mlflow project
      # Menggantikan 'python modelling.py' dengan perintah MLflow Project
      run: mlflow run MLProject/ --no-conda

    - name: Get latest MLflow run_id
      run: |
        # Pastikan skrip kamu menghasilkan file RUN_ID.txt di folder yang tepat
        RUN_ID=$(cat MLProject/RUN_ID.txt)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    # Langkah Tambahan untuk LEVEL ADVANCED (Menyimpan Artefak)
    - name: Upload model artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifact
        path: |
          mlruns/
          MLProject/

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker Model
      # Menggunakan run_id yang didapat dari langkah sebelumnya
      run: mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/iris-model:latest"

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/iris-model:latest